services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
  
  parser:
    build:
      context: ./parser/
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    volumes:
    - ./parser/coordinates.py:/app/coordinates.py
    - ./parser/main.py:/app/main.py
  
  fastapi:
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    depends_on:
      - mongo
    ports:
      - 8000:8000
    volumes:
      - ./api/main.py:/app/main.py

volumes:
  mongodb_data:
